# Generated by Django 5.2.15 on 2026-06-27 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Donanım Adı')),
                ('asset_type', models.CharField(choices=[('laptop', 'Dizüstü Bilgisayar'), ('desktop', 'Masaüstü Bilgisayar'), ('monitor', 'Monitör'), ('printer', 'Yazıcı'), ('mobile', 'Mobil Cihaz'), ('peripherals', 'Çevre Birimi')], db_index=True, default='laptop', max_length=20, verbose_name='Tür')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Seri No')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zimmet')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Satın Alma')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Garanti Bitiş')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('repair', 'Tamirde'), ('retired', 'Hurda')], db_index=True, default='active', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Donanım',
                'verbose_name_plural': 'Donanımlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yazılım Adı')),
                ('license_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lisans Anahtarı')),
                ('total_slots', models.IntegerField(default=1, verbose_name='Toplam Kullanım')),
                ('used_slots', models.IntegerField(default=0, verbose_name='Kullanılan')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='Bitiş Tarihi')),
                ('vendor', models.CharField(max_length=100, verbose_name='Üretici')),
                ('is_subscription', models.BooleanField(default=True, verbose_name='Abonelik')),
            ],
            options={
                'verbose_name': 'Lisans',
                'verbose_name_plural': 'Lisanslar',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='RemoteProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Probe/Agent Adı')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokasyon/Şube')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Probe IP Adresi')),
                ('target_subnet', models.CharField(blank=True, help_text='Örn: 192.168.1.0/24', max_length=50, null=True, verbose_name='Tarama Hedef Subnet')),
                ('agent_version', models.CharField(default='1.0.0', max_length=50, verbose_name='Ajan Sürümü')),
                ('status', models.CharField(choices=[('online', 'Çevrimiçi'), ('offline', 'Bağlantı Koptu'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=20, verbose_name='Durum')),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True, verbose_name='Son İletişim (Heartbeat)')),
            ],
            options={
                'verbose_name': 'Uzak Probe (Ajan)',
                'verbose_name_plural': 'Uzak Probelar (Ajanlar)',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('description', models.TextField(verbose_name='Açıklama ve Şartlar')),
                ('icon', models.CharField(default='mdi:laptop', max_length=50, verbose_name='Iconify İkon Kodu')),
                ('category', models.CharField(choices=[('Yazılım', 'Yazılım ve Lisans'), ('Donanım', 'Donanım Tahsisi'), ('Erişim', 'Ağ ve VPN Erişimi'), ('Diger', 'Diğer Hizmetler')], default='Yazılım', max_length=50, verbose_name='Kategori')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Yönetici Onayı Gerekli Mi?')),
            ],
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('vendor_name', models.CharField(db_index=True, max_length=100, verbose_name='Tedarikçi')),
                ('contract_type', models.CharField(choices=[('internet', 'İnternet'), ('cloud', 'Bulut'), ('maintenance', 'Bakım'), ('software', 'Yazılım'), ('other', 'Diğer')], default='internet', max_length=20, verbose_name='Tür')),
                ('sla_level', models.CharField(choices=[('24_7', '7/24'), ('8_5_nbd', '8x5 NBD'), ('standard', 'Standart')], default='standard', max_length=20, verbose_name='SLA')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(db_index=True, verbose_name='Bitiş Tarihi')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maliyet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cihaz Adı')),
                ('device_type', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('Server', 'Sunucu'), ('PC', 'Bilgisayar')], db_index=True, max_length=50, verbose_name='Cihaz Türü')),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='MAC Adresi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Durum')),
                ('monitoring_mode', models.CharField(choices=[('monitoring', 'İzleme'), ('error', 'Hata'), ('offline', 'Çevrimdışı')], db_index=True, default='monitoring', max_length=20, verbose_name='İzleme Modu')),
                ('rack_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kabin Adı')),
                ('position_u', models.IntegerField(blank=True, null=True, verbose_name='Başlangıç U')),
                ('height_u', models.IntegerField(default=1, verbose_name='Yükseklik')),
                ('vendor', models.CharField(choices=[('cisco', 'Cisco IOS'), ('huawei', 'Huawei VRP'), ('other', 'Diğer')], default='cisco', max_length=20, verbose_name='Üretici')),
                ('ssh_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanıcı Adı')),
                ('ssh_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parola')),
                ('enable_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enable Parolası')),
                ('os_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşletim Sistemi')),
                ('cpu_usage', models.IntegerField(default=0, verbose_name='CPU Kullanımı')),
                ('ram_usage', models.IntegerField(default=0, verbose_name='RAM Kullanımı')),
                ('last_polled', models.DateTimeField(blank=True, null=True, verbose_name='Son Denetim')),
                ('cpu_alarm_threshold', models.IntegerField(default=90, verbose_name='Kritik CPU Eşiği (%)')),
                ('ram_alarm_threshold', models.IntegerField(default=90, verbose_name='Kritik RAM Eşiği (%)')),
                ('parent_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_devices', to='inventory.device', verbose_name='Üst Cihaz')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('target_ip', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Hedef IP')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Üretici')),
                ('config_payload', models.TextField(verbose_name='Konfigürasyon')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('failed', 'Başarısız')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('execution_log', models.TextField(blank=True, null=True, verbose_name='İşlem Logu')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL, verbose_name='Yönetici')),
                ('target_devices', models.ManyToManyField(blank=True, related_name='change_requests', to='inventory.device', verbose_name='Hedef Cihazlar')),
            ],
            options={
                'verbose_name': 'Değişiklik',
                'verbose_name_plural': 'Değişiklikler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_text', models.TextField(verbose_name='Konfigürasyon')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('backed_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='inventory.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Yedek',
                'verbose_name_plural': 'Yedekler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(default=0.0, help_text='Yüzdelik CPU Kullanımı')),
                ('ram_usage', models.FloatField(default=0.0, help_text='Yüzdelik RAM Kullanımı')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Yüzdelik Disk Kullanımı')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='inventory.device')),
            ],
            options={
                'verbose_name': 'Performans Logu',
                'verbose_name_plural': 'Performans Logları',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP Adresi')),
                ('is_allocated', models.BooleanField(db_index=True, default=False, verbose_name='Tahsis Durumu')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device', verbose_name='Bağlı Cihaz')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('category', models.CharField(choices=[('network', 'Ağ'), ('hardware', 'Donanım'), ('software', 'Yazılım'), ('account', 'Hesap'), ('other', 'Diğer')], db_index=True, default='other', max_length=20, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('views_count', models.IntegerField(default=0, verbose_name='Görüntülenme')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Faydalı')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-helpful_count', '-views_count'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONFIG', 'Konfigürasyon'), ('SCAN', 'Ağ Taraması'), ('IPAM', 'IP İşlemi'), ('TICKET', 'Talep İşlemi'), ('SYSTEM', 'Sistem Olayı')], db_index=True, max_length=20, verbose_name='İşlem Türü')),
                ('details', models.TextField(verbose_name='Detay')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Detay')),
                ('priority', models.CharField(choices=[('Kritik', 'Kritik'), ('Yuksek', 'Yüksek'), ('Orta', 'Orta'), ('Dusuk', 'Düşük')], db_index=True, default='Orta', max_length=20, verbose_name='Öncelik')),
                ('category', models.CharField(choices=[('Donanim', 'Donanım'), ('Yazilim', 'Yazılım'), ('Ag', 'Ağ'), ('Diger', 'Diğer')], db_index=True, default='Diger', max_length=20, verbose_name='Kategori')),
                ('status', models.CharField(choices=[('Acik', 'Açık'), ('Inceleniyor', 'İnceleniyor'), ('Cozuldu', 'Çözüldü'), ('Kapatildi', 'Kapatıldı')], db_index=True, default='Acik', max_length=20, verbose_name='Durum')),
                ('is_escalated', models.BooleanField(db_index=True, default=False, verbose_name='Eskale Edildi Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Kapanış Tarihi')),
                ('sla_deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='SLA Süresi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device', verbose_name='İlgili Cihaz')),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Bağlantı')),
                ('notification_type', models.CharField(choices=[('info', 'Bilgi'), ('assignment', 'Atama'), ('comment', 'Yorum'), ('status', 'Durum'), ('closed', 'Kapanış'), ('sla_breach', 'SLA İhlali')], default='info', max_length=20, verbose_name='Tür')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.ticket', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/', verbose_name='Dosya')),
                ('filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.ticket', verbose_name='Talep')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Talep Eki',
                'verbose_name_plural': 'Talep Ekleri',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='mdi:tag-outline', max_length=50, verbose_name='İkon')),
                ('sla_hours', models.PositiveIntegerField(default=24, verbose_name='SLA (Saat)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('auto_assign_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_categories', to='auth.group', verbose_name='Otomatik Atama Grubu')),
            ],
            options={
                'verbose_name': 'Talep Kategorisi',
                'verbose_name_plural': 'Talep Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='inventory.ticketcategory', verbose_name='Kategori (Yönetilebilir)'),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mesaj')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Dahili Not (Sadece Personel)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.ticket', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Talep Yorumu',
                'verbose_name_plural': 'Talep Yorumları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('bio', models.TextField(blank=True, verbose_name='Biyografi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(verbose_name='Port No')),
                ('name', models.CharField(default='FastEthernet0/X', max_length=50, verbose_name='Port Adı')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled')], default='down', max_length=20, verbose_name='Durum')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Açıklama')),
                ('connected_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_port', to='inventory.itasset', verbose_name='Bağlı Cihaz')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Portlar',
                'ordering': ['device', 'port_number'],
                'unique_together': {('device', 'port_number')},
            },
        ),
    ]
