# Generated by Django 5.2.15 on 2026-06-27 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DLPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80, verbose_name='Kaynak')),
                ('rule', models.CharField(max_length=120, verbose_name='Kural')),
                ('severity', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Seviye')),
                ('excerpt', models.TextField(blank=True, verbose_name='Örnek')),
                ('blocked', models.BooleanField(default=False, verbose_name='Engellendi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'DLP Olayı',
                'verbose_name_plural': 'DLP Olayları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Müşteri/Lokasyon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Enlem')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Boylam')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Rota Sırası')),
                ('distance_km', models.FloatField(default=0.0, verbose_name='Mesafe (km)')),
                ('vehicle_model', models.CharField(default='Standart Servis Aracı', max_length=80, verbose_name='Araç Modeli')),
                ('fuel_l_per_100km', models.FloatField(default=7.5, verbose_name='Yakıt (L/100km)')),
                ('ac_multiplier', models.FloatField(default=1.08, verbose_name='Klima Çarpanı')),
                ('estimated_fuel_l', models.FloatField(default=0.0, verbose_name='Tahmini Yakıt (L)')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('in_progress', 'Yolda'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], db_index=True, default='planned', max_length=20, verbose_name='Durum')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Planlanan Zaman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to=settings.AUTH_USER_MODEL, verbose_name='Teknisyen')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='inventory.ticket', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Saha Ziyareti',
                'verbose_name_plural': 'Saha Ziyaretleri',
                'ordering': ['order_index', 'scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50, verbose_name='Ağ Bloğu')),
                ('method', models.CharField(choices=[('arp', 'ARP'), ('ping', 'Ping'), ('raw_socket', 'Raw Socket'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20, verbose_name='Yöntem')),
                ('total_hosts', models.PositiveIntegerField(default=0, verbose_name='Toplam Host')),
                ('active_hosts', models.PositiveIntegerField(default=0, verbose_name='Aktif Host')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Süre (ms)')),
                ('error', models.TextField(blank=True, verbose_name='Hata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Taramayı Başlatan')),
            ],
            options={
                'verbose_name': 'Ağ Taraması',
                'verbose_name_plural': 'Ağ Taramaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScanHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Host Adı')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Üretici')),
                ('detected_by', models.CharField(blank=True, max_length=80, verbose_name='Tespit Yöntemi')),
                ('latency_ms', models.FloatField(blank=True, null=True, verbose_name='Gecikme (ms)')),
                ('raw_socket_open', models.BooleanField(default=False, verbose_name='Raw Socket Yanıtı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='inventory.networkscan', verbose_name='Tarama')),
            ],
            options={
                'verbose_name': 'Tarama Hostu',
                'verbose_name_plural': 'Tarama Hostları',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Fırsat')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Müşteri')),
                ('stage', models.CharField(choices=[('lead', 'Yeni Fırsat'), ('qualified', 'Nitelikli'), ('proposal', 'Teklif'), ('negotiation', 'Pazarlık'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi')], db_index=True, default='lead', max_length=20, verbose_name='Aşama')),
                ('potential_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Potansiyel Gelir')),
                ('probability', models.PositiveIntegerField(default=20, verbose_name='Olasılık (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Satış Fırsatı',
                'verbose_name_plural': 'Satış Fırsatları',
                'ordering': ['stage', 'position', '-updated_at'],
            },
        ),
    ]
