# Generated by Django 5.2.15 on 2026-06-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_repair_ticket_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kalem Adı')),
                ('category', models.CharField(choices=[('toner', 'Toner/Kartuş'), ('label', 'Etiket/Ribon'), ('spare', 'Yedek Parça'), ('cable', 'Kablo/Adaptör'), ('backup_media', 'Yedekleme Medyası'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='Kategori')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='Stok Kodu')),
                ('compatible_with', models.CharField(blank=True, max_length=200, verbose_name='Uyumlu Cihaz/Model')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Depo/Lokasyon')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Mevcut Stok')),
                ('minimum_quantity', models.PositiveIntegerField(default=1, verbose_name='Minimum Stok')),
                ('unit', models.CharField(default='adet', max_length=30, verbose_name='Birim')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Tedarikçi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Sarf/Yedek Stok',
                'verbose_name_plural': 'Sarf/Yedek Stokları',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FactoryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Alan/Hat Adı')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kod')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('criticality', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Kritiklik')),
                ('manager_name', models.CharField(blank=True, max_length=120, verbose_name='Sorumlu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Fabrika Alanı',
                'verbose_name_plural': 'Fabrika Alanları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeITProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Personel')),
                ('department', models.CharField(max_length=120, verbose_name='Departman')),
                ('process_type', models.CharField(choices=[('onboarding', 'İşe Giriş'), ('offboarding', 'İşten Çıkış'), ('transfer', 'Departman Değişikliği')], db_index=True, max_length=30, verbose_name='Süreç')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('waiting', 'Beklemede'), ('done', 'Tamamlandı'), ('cancelled', 'İptal')], db_index=True, default='open', max_length=20, verbose_name='Durum')),
                ('ad_account_done', models.BooleanField(default=False, verbose_name='AD/Hesap')),
                ('email_done', models.BooleanField(default=False, verbose_name='E-posta')),
                ('erp_done', models.BooleanField(default=False, verbose_name='ERP/MES')),
                ('vpn_done', models.BooleanField(default=False, verbose_name='VPN/Uzak Erişim')),
                ('device_done', models.BooleanField(default=False, verbose_name='Cihaz/Zimmet')),
                ('badge_done', models.BooleanField(default=False, verbose_name='Kart/Yetki')),
                ('data_backup_done', models.BooleanField(default=False, verbose_name='Veri Yedek/Devir')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employee_processes', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu IT')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_employee_processes', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_processes', to='inventory.factoryarea', verbose_name='Fabrika Alanı')),
            ],
            options={
                'verbose_name': 'Personel IT Süreci',
                'verbose_name_plural': 'Personel IT Süreçleri',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='İş Başlığı')),
                ('task_type', models.CharField(choices=[('backup', 'Yedek Kontrolü'), ('patch', 'Patch/Güncelleme'), ('printer', 'Yazıcı/Barkod'), ('network', 'Ağ Kontrolü'), ('server', 'Sunucu/Storage'), ('security', 'Güvenlik'), ('production_line', 'Üretim Hattı IT'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='İş Tipi')),
                ('frequency_days', models.PositiveIntegerField(default=30, verbose_name='Periyot (Gün)')),
                ('last_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Tamamlanma')),
                ('next_due_at', models.DateTimeField(db_index=True, verbose_name='Sonraki Tarih')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('in_progress', 'Devam Ediyor'), ('done', 'Tamamlandı'), ('blocked', 'Blokeli')], db_index=True, default='planned', max_length=20, verbose_name='Durum')),
                ('checklist', models.TextField(blank=True, verbose_name='Checklist')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='inventory.itasset', verbose_name='Varlık')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='inventory.device', verbose_name='Cihaz')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='inventory.factoryarea', verbose_name='Fabrika Alanı')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Bakım/Checklist İşi',
                'verbose_name_plural': 'Bakım/Checklist İşleri',
                'ordering': ['next_due_at', 'status'],
            },
        ),
    ]
