# Generated by Django 5.2.15 on 2026-06-27 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_consumableitem_factoryarea_employeeitprocess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Personel')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departman')),
                ('action', models.CharField(choices=[('assign', 'Zimmet Verme'), ('return', 'Zimmet İade'), ('transfer', 'Transfer')], db_index=True, default='assign', max_length=20, verbose_name='İşlem')),
                ('handover_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Durum Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='inventory.itasset', verbose_name='Varlık')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handovers', to='inventory.factoryarea', verbose_name='Fabrika Alanı')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handovers', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Zimmet Kaydı',
                'verbose_name_plural': 'Zimmet Kayıtları',
                'ordering': ['-handover_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupJobMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Yedekleme Adı')),
                ('system_type', models.CharField(choices=[('server', 'Sunucu'), ('database', 'Veritabanı'), ('application', 'Uygulama'), ('vm', 'Sanal Makine'), ('file', 'Dosya Paylaşımı')], db_index=True, default='server', max_length=20, verbose_name='Sistem Tipi')),
                ('target_host', models.CharField(blank=True, max_length=120, verbose_name='Hedef Sunucu')),
                ('schedule_description', models.CharField(default='Günlük 02:00', max_length=120, verbose_name='Plan')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Çalışma')),
                ('last_status', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız'), ('warning', 'Uyarı'), ('missed', 'Kaçırıldı'), ('unknown', 'Bilinmiyor')], db_index=True, default='unknown', max_length=20, verbose_name='Son Durum')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Sonraki Çalışma')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='Saklama (Gün)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Yedekleme İşi',
                'verbose_name_plural': 'Yedekleme İşleri',
                'ordering': ['last_status', 'next_run_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnCallShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Başlangıç')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Bitiş')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='İletişim')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Birincil Nöbetçi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Nöbetçi')),
            ],
            options={
                'verbose_name': 'Nöbet Kaydı',
                'verbose_name_plural': 'Nöbet Kayıtları',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Talep Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('category', models.CharField(choices=[('hardware', 'Donanım'), ('software', 'Yazılım'), ('service', 'Hizmet'), ('consumable', 'Sarf Malzeme')], db_index=True, default='hardware', max_length=20, verbose_name='Kategori')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tahmini Maliyet')),
                ('vendor_name', models.CharField(blank=True, max_length=120, verbose_name='Tedarikçi')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('ordered', 'Sipariş Verildi'), ('received', 'Teslim Alındı'), ('rejected', 'Reddedildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='İhtiyaç Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procurements', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='inventory.factoryarea', verbose_name='Fabrika Alanı')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Konu')),
                ('vendor_name', models.CharField(max_length=120, verbose_name='Tedarikçi')),
                ('case_number', models.CharField(blank=True, max_length=80, verbose_name='Tedarikçi Vaka No')),
                ('priority', models.CharField(choices=[('Kritik', 'Kritik'), ('Yuksek', 'Yüksek'), ('Orta', 'Orta'), ('Dusuk', 'Düşük')], db_index=True, default='Orta', max_length=20, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('waiting_vendor', 'Tedarikçi Bekleniyor'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], db_index=True, default='open', max_length=20, verbose_name='Durum')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Açılış')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözüm Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_support_cases', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu IT')),
                ('vendor_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='inventory.vendorcontract', verbose_name='Sözleşme')),
            ],
            options={
                'verbose_name': 'Tedarikçi Destek Kaydı',
                'verbose_name_plural': 'Tedarikçi Destek Kayıtları',
                'ordering': ['status', '-opened_at'],
            },
        ),
    ]
