# Generated by Django 5.2.15 on 2026-06-29 04:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_assethandover_backupjobmonitor_oncallshift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Kullanıcı/Personel')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departman')),
                ('access_type', models.CharField(choices=[('vpn', 'VPN'), ('file_share', 'Dosya Paylaşımı'), ('erp', 'ERP/MES'), ('email_group', 'E-posta Grubu'), ('application', 'Uygulama'), ('admin', 'Geçici Admin Yetkisi'), ('other', 'Diğer')], db_index=True, default='application', max_length=30, verbose_name='Erişim Tipi')),
                ('target_system', models.CharField(max_length=150, verbose_name='Hedef Sistem/Paylaşım')),
                ('justification', models.TextField(verbose_name='Gerekçe')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('provisioned', 'Yetki Verildi'), ('rejected', 'Reddedildi'), ('revoked', 'Geri Alındı')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Süre Sonu')),
                ('provisioned_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetki Verilme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name': 'Erişim Talebi',
                'verbose_name_plural': 'Erişim Talepleri',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MajorIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Olay Başlığı')),
                ('severity', models.CharField(choices=[('sev1', 'SEV1 - Üretim Durdu'), ('sev2', 'SEV2 - Kritik Etki'), ('sev3', 'SEV3 - Sınırlı Etki'), ('sev4', 'SEV4 - Düşük Etki')], db_index=True, default='sev3', max_length=20, verbose_name='Seviye')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('war_room', 'Savaş Odası'), ('monitoring', 'İzlemede'), ('resolved', 'Çözüldü'), ('postmortem', 'Post-mortem'), ('closed', 'Kapatıldı')], db_index=True, default='open', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözüm')),
                ('impact_summary', models.TextField(blank=True, verbose_name='Etki Özeti')),
                ('root_cause', models.TextField(blank=True, verbose_name='Kök Neden')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='Kalıcı Aksiyonlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_incidents', to='inventory.factoryarea', verbose_name='Etkilenen Alan')),
                ('incident_commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Olay Lideri')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_incidents', to='inventory.ticket', verbose_name='İlgili Talep')),
            ],
            options={
                'verbose_name': 'Major Incident',
                'verbose_name_plural': 'Major Incident Kayıtları',
                'ordering': ['status', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterFleetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Cihaz Adı')),
                ('device_kind', models.CharField(choices=[('printer', 'Yazıcı'), ('barcode', 'Barkod Yazıcı'), ('label', 'Etiket Yazıcı'), ('scanner', 'Tarayıcı'), ('mfp', 'Çok Fonksiyonlu')], db_index=True, default='printer', max_length=20, verbose_name='Tip')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Seri No')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('page_counter', models.PositiveIntegerField(default=0, verbose_name='Sayaç')),
                ('toner_level_percent', models.PositiveIntegerField(default=100, verbose_name='Toner/Ribon (%)')),
                ('status', models.CharField(choices=[('online', 'Aktif'), ('warning', 'Uyarı'), ('maintenance', 'Bakımda'), ('offline', 'Çevrimdışı'), ('retired', 'Emekli')], db_index=True, default='online', max_length=20, verbose_name='Durum')),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Bakım')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='inventory.consumableitem', verbose_name='Toner/Ribon')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='inventory.factoryarea', verbose_name='Alan')),
            ],
            options={
                'verbose_name': 'Yazıcı Filosu',
                'verbose_name_plural': 'Yazıcı Filosu',
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('category', models.CharField(choices=[('incident', 'Olay Müdahalesi'), ('maintenance', 'Bakım'), ('security', 'Güvenlik'), ('backup', 'Yedekleme'), ('onboarding', 'Personel Süreci'), ('network', 'Ağ'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='Kategori')),
                ('related_device_type', models.CharField(blank=True, max_length=80, verbose_name='İlgili Cihaz Tipi')),
                ('steps', models.TextField(verbose_name='Adımlar')),
                ('rollback_steps', models.TextField(blank=True, verbose_name='Geri Dönüş Adımları')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiyon')),
                ('last_reviewed_at', models.DateField(blank=True, null=True, verbose_name='Son Gözden Geçirme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbooks', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Runbook / SOP',
                'verbose_name_plural': 'Runbook / SOP Kayıtları',
                'ordering': ['category', 'title'],
            },
        ),
    ]
