# Generated by Django 5.2.15 on 2026-06-29 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_accessrequest_majorincident_printerfleetitem_runbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kanal Adı')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departman')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Departman Chat Kanalı',
                'verbose_name_plural': 'Departman Chat Kanalları',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Uygulama Adı')),
                ('app_type', models.CharField(choices=[('erp', 'ERP'), ('mes', 'MES'), ('crm', 'CRM'), ('hr', 'İK'), ('accounting', 'Muhasebe'), ('document', 'Doküman'), ('reporting', 'Raporlama'), ('other', 'Diğer')], db_index=True, default='other', max_length=20, verbose_name='Tip')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('owner_department', models.CharField(blank=True, max_length=120, verbose_name='Sahip Departman')),
                ('sso_enabled', models.BooleanField(default=False, verbose_name='SSO Aktif')),
                ('status', models.CharField(choices=[('online', 'Aktif'), ('degraded', 'Kısmi Sorun'), ('offline', 'Çevrimdışı'), ('maintenance', 'Bakımda')], db_index=True, default='online', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('technical_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_apps', to=settings.AUTH_USER_MODEL, verbose_name='Teknik Sorumlu')),
            ],
            options={
                'verbose_name': 'İş Uygulaması',
                'verbose_name_plural': 'İş Uygulamaları',
                'ordering': ['app_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kamera/NVR Adı')),
                ('device_type', models.CharField(choices=[('ip_camera', 'IP Kamera'), ('nvr', 'NVR'), ('dvr', 'DVR'), ('vms', 'VMS Sunucusu')], db_index=True, default='ip_camera', max_length=20, verbose_name='Tip')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('stream_url', models.CharField(blank=True, max_length=500, verbose_name='Canlı İzleme URL')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lokasyon')),
                ('recording_days', models.PositiveIntegerField(default=15, verbose_name='Kayıt Saklama (Gün)')),
                ('status', models.CharField(choices=[('online', 'Aktif'), ('warning', 'Uyarı'), ('offline', 'Çevrimdışı'), ('maintenance', 'Bakımda')], db_index=True, default='online', max_length=20, verbose_name='Durum')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Kontrol')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='inventory.factoryarea', verbose_name='Fabrika Alanı')),
            ],
            options={
                'verbose_name': 'Kamera Sistemi',
                'verbose_name_plural': 'Kamera Sistemleri',
                'ordering': ['status', 'location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_announcement', models.BooleanField(default=False, verbose_name='Duyuru')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yazan')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inventory.departmentchannel', verbose_name='Kanal')),
            ],
            options={
                'verbose_name': 'Departman Mesajı',
                'verbose_name_plural': 'Departman Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Kullanıcı/Personel')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departman')),
                ('access_method', models.CharField(choices=[('vpn', 'VPN'), ('rdp', 'RDP'), ('ssh', 'SSH'), ('ztna', 'Zero Trust'), ('web_portal', 'Web Portal')], db_index=True, default='vpn', max_length=20, verbose_name='Erişim Yöntemi')),
                ('target_resource', models.CharField(max_length=180, verbose_name='Hedef Kaynak')),
                ('gateway', models.CharField(blank=True, max_length=180, verbose_name='VPN Gateway / Portal')),
                ('allowed_source', models.CharField(blank=True, max_length=180, verbose_name='İzinli Kaynak IP')),
                ('mfa_required', models.BooleanField(default=True, verbose_name='MFA Zorunlu')),
                ('status', models.CharField(choices=[('requested', 'Talep Edildi'), ('approved', 'Onaylandı'), ('active', 'Aktif'), ('suspended', 'Askıya Alındı'), ('expired', 'Süresi Doldu'), ('revoked', 'İptal Edildi')], db_index=True, default='requested', max_length=20, verbose_name='Durum')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Süre Sonu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_remote_access', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
            ],
            options={
                'verbose_name': 'Uzaktan Erişim Yetkisi',
                'verbose_name_plural': 'Uzaktan Erişim Yetkileri',
                'ordering': ['status', 'expires_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Rapor Adı')),
                ('report_type', models.CharField(choices=[('inventory', 'Envanter'), ('ticket', 'Ticket/SLA'), ('security', 'Güvenlik'), ('factory', 'Fabrika Operasyon'), ('asset', 'Zimmet'), ('backup', 'Yedekleme'), ('custom', 'Özel')], db_index=True, default='custom', max_length=20, verbose_name='Rapor Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('query_notes', models.TextField(blank=True, verbose_name='Veri Kaynağı / Filtre Notu')),
                ('output_format', models.CharField(default='pdf,csv', max_length=20, verbose_name='Çıktı Formatları')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Rapor Şablonu',
                'verbose_name_plural': 'Rapor Şablonları',
                'ordering': ['report_type', 'title'],
            },
        ),
    ]
