# Generated by Django 5.2.15 on 2026-06-29 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_departmentchannel_businessapplication_cameradevice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('event_type', models.CharField(choices=[('maintenance', 'Bakım'), ('change', 'Değişiklik'), ('outage', 'Planlı Kesinti'), ('release', 'Sürüm Geçişi'), ('audit', 'Denetim')], db_index=True, default='maintenance', max_length=20, verbose_name='Tip')),
                ('risk_level', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Risk')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Başlangıç')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Bitiş')),
                ('expected_impact', models.TextField(blank=True, verbose_name='Beklenen Etki')),
                ('rollback_plan', models.TextField(blank=True, verbose_name='Geri Dönüş Planı')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('approved', 'Onaylandı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], db_index=True, default='planned', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='inventory.changerequest', verbose_name='CAB Kaydı')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='inventory.factoryarea', verbose_name='Etkilenen Alan')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Değişiklik/Bakım Takvimi',
                'verbose_name_plural': 'Değişiklik/Bakım Takvimi',
                'ordering': ['start_at', 'risk_level'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Kontrol')),
                ('framework', models.CharField(choices=[('iso27001', 'ISO 27001'), ('kvkk', 'KVKK'), ('internal', 'İç Denetim'), ('backup', 'Yedekleme Politikası'), ('access', 'Erişim Denetimi'), ('other', 'Diğer')], db_index=True, default='internal', max_length=20, verbose_name='Çerçeve')),
                ('status', models.CharField(choices=[('compliant', 'Uygun'), ('gap', 'Açık Var'), ('in_progress', 'Devam Ediyor'), ('not_checked', 'Kontrol Edilmedi')], db_index=True, default='not_checked', max_length=20, verbose_name='Durum')),
                ('evidence', models.TextField(blank=True, verbose_name='Kanıt / Bulgu')),
                ('remediation_plan', models.TextField(blank=True, verbose_name='İyileştirme Planı')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('last_checked_at', models.DateField(blank=True, null=True, verbose_name='Son Kontrol')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_controls', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Uyum Kontrolü',
                'verbose_name_plural': 'Uyum Kontrolleri',
                'ordering': ['status', 'due_date', 'framework'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOutputJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='İş Başlığı')),
                ('job_type', models.CharField(choices=[('report', 'Rapor'), ('handover', 'Zimmet Formu'), ('maintenance', 'Bakım Formu'), ('incident', 'Olay Raporu'), ('audit', 'Denetim Kanıtı'), ('custom', 'Özel')], db_index=True, default='report', max_length=20, verbose_name='Tip')),
                ('output_format', models.CharField(default='pdf', max_length=20, verbose_name='Format')),
                ('status', models.CharField(choices=[('queued', 'Kuyrukta'), ('processing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('delivered', 'Teslim Edildi'), ('failed', 'Hata')], db_index=True, default='queued', max_length=20, verbose_name='Durum')),
                ('file', models.FileField(blank=True, null=True, upload_to='document_outputs/%Y/%m/', verbose_name='Dosya')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_jobs', to='inventory.reporttemplate', verbose_name='Rapor Şablonu')),
            ],
            options={
                'verbose_name': 'Doküman/Çıktı İşi',
                'verbose_name_plural': 'Doküman/Çıktı İşleri',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Entegrasyon')),
                ('integration_type', models.CharField(choices=[('odoo', 'Odoo'), ('erp', 'ERP'), ('mes', 'MES'), ('ldap', 'LDAP/AD'), ('smtp', 'SMTP'), ('camera_vms', 'Kamera VMS'), ('backup', 'Yedekleme'), ('api', 'API'), ('other', 'Diğer')], db_index=True, default='api', max_length=20, verbose_name='Tip')),
                ('endpoint_url', models.CharField(blank=True, max_length=500, verbose_name='Endpoint/URL')),
                ('last_status', models.CharField(choices=[('healthy', 'Sağlıklı'), ('degraded', 'Yavaş/Sorunlu'), ('down', 'Çalışmıyor'), ('unknown', 'Bilinmiyor')], db_index=True, default='unknown', max_length=20, verbose_name='Son Durum')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Kontrol')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Yanıt Süresi (ms)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_checks', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Entegrasyon Sağlık Kontrolü',
                'verbose_name_plural': 'Entegrasyon Sağlık Kontrolleri',
                'ordering': ['last_status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='İlişki Adı')),
                ('dependency_type', models.CharField(choices=[('runs_on', 'Üzerinde Çalışır'), ('connects_to', 'Bağlanır'), ('depends_on', 'Bağımlı'), ('backs_up_to', 'Yedeklenir'), ('monitors', 'İzler')], db_index=True, default='depends_on', max_length=20, verbose_name='Bağımlılık Tipi')),
                ('criticality', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Kritiklik')),
                ('impact_description', models.TextField(blank=True, verbose_name='Etki Açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('business_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='inventory.businessapplication', verbose_name='Uygulama')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_dependencies', to='inventory.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'CMDB Bağımlılığı',
                'verbose_name_plural': 'CMDB Bağımlılıkları',
                'ordering': ['criticality', 'business_application__name'],
            },
        ),
    ]
