# Generated by Django 5.2.15 on 2026-06-30 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_changecalendarevent_compliancecontrol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bağlantı Adı')),
                ('directory_type', models.CharField(choices=[('active_directory', 'Active Directory'), ('ldap', 'LDAP'), ('azure_ad', 'Azure AD / Entra ID'), ('manual', 'Manuel / CSV')], db_index=True, default='active_directory', max_length=30, verbose_name='Tip')),
                ('server_uri', models.CharField(blank=True, max_length=300, verbose_name='Sunucu URI')),
                ('base_dn', models.CharField(blank=True, max_length=300, verbose_name='Base DN')),
                ('bind_username', models.CharField(blank=True, max_length=180, verbose_name='Bind Kullanıcısı')),
                ('user_filter', models.CharField(default='(objectClass=user)', max_length=300, verbose_name='Kullanıcı Filtresi')),
                ('group_filter', models.CharField(default='(objectClass=group)', max_length=300, verbose_name='Grup Filtresi')),
                ('sync_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Sync Aktif')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Sync')),
                ('last_sync_status', models.CharField(choices=[('not_configured', 'Yapılandırılmadı'), ('healthy', 'Sağlıklı'), ('warning', 'Uyarı'), ('failed', 'Hata')], db_index=True, default='not_configured', max_length=20, verbose_name='Son Durum')),
                ('last_sync_message', models.TextField(blank=True, verbose_name='Son Sync Mesajı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_connections', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Directory Bağlantısı',
                'verbose_name_plural': 'Directory Bağlantıları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=180, verbose_name='Grup Adı')),
                ('distinguished_name', models.CharField(blank=True, max_length=500, verbose_name='DN')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('mapped_role', models.CharField(blank=True, max_length=120, verbose_name='OmniOps Rolü')),
                ('mapped_system', models.CharField(blank=True, max_length=150, verbose_name='İş Uygulaması / Sistem')),
                ('risk_level', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Risk')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('is_privileged', models.BooleanField(db_index=True, default=False, verbose_name='Ayrıcalıklı Grup')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='inventory.directoryconnection', verbose_name='Directory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_directory_groups', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Directory Grubu',
                'verbose_name_plural': 'Directory Grupları',
                'ordering': ['-is_privileged', 'risk_level', 'name'],
                'unique_together': {('connection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DirectoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Kullanıcı Adı')),
                ('display_name', models.CharField(blank=True, max_length=180, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('department', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Departman')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Unvan')),
                ('manager', models.CharField(blank=True, max_length=180, verbose_name='Yönetici')),
                ('distinguished_name', models.CharField(blank=True, max_length=500, verbose_name='DN')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('disabled', 'Pasif'), ('locked', 'Kilitli'), ('expired', 'Süresi Doldu'), ('unknown', 'Bilinmiyor')], db_index=True, default='unknown', max_length=20, verbose_name='Durum')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA')),
                ('password_last_set_at', models.DateTimeField(blank=True, null=True, verbose_name='Parola Son Değişim')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Oturum')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Sync Görülme')),
                ('risk_note', models.TextField(blank=True, verbose_name='Risk Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='inventory.directoryconnection', verbose_name='Directory')),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='inventory.directorygroup', verbose_name='Gruplar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='OmniOps Kullanıcısı')),
            ],
            options={
                'verbose_name': 'Directory Kullanıcısı',
                'verbose_name_plural': 'Directory Kullanıcıları',
                'ordering': ['status', 'department', 'username'],
                'unique_together': {('connection', 'username')},
            },
        ),
        migrations.CreateModel(
            name='EndpointDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=150, verbose_name='Hostname')),
                ('assigned_to_text', models.CharField(blank=True, max_length=180, verbose_name='Zimmetli')),
                ('device_type', models.CharField(choices=[('desktop', 'Masaüstü'), ('laptop', 'Laptop'), ('mobile', 'Mobil'), ('tablet', 'Tablet'), ('thin_client', 'Thin Client'), ('industrial_pc', 'Endüstriyel PC'), ('other', 'Diğer')], db_index=True, default='laptop', max_length=30, verbose_name='Tip')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Seri No')),
                ('os_name', models.CharField(blank=True, max_length=150, verbose_name='İşletim Sistemi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('status', models.CharField(choices=[('compliant', 'Uyumlu'), ('attention', 'Dikkat'), ('non_compliant', 'Uyumsuz'), ('lost', 'Kayıp'), ('retired', 'Emekli')], db_index=True, default='attention', max_length=20, verbose_name='Uyum Durumu')),
                ('antivirus_ok', models.BooleanField(default=False, verbose_name='Antivirüs OK')),
                ('disk_encrypted', models.BooleanField(default=False, verbose_name='Disk Şifreli')),
                ('patch_level', models.CharField(blank=True, max_length=120, verbose_name='Patch Seviyesi')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint_records', to='inventory.itasset', verbose_name='Varlık')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='inventory.directoryuser', verbose_name='Directory Kullanıcısı')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='inventory.factoryarea', verbose_name='Alan')),
            ],
            options={
                'verbose_name': 'Uç Nokta Cihazı',
                'verbose_name_plural': 'Uç Nokta Cihazları',
                'ordering': ['status', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='IdentityLifecycleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('process_type', models.CharField(choices=[('onboarding', 'İşe Başlama'), ('offboarding', 'İşten Çıkış'), ('transfer', 'Departman Transferi'), ('access_review', 'Erişim Gözden Geçirme')], db_index=True, default='onboarding', max_length=30, verbose_name='Süreç')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Personel')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departman')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('waiting_approval', 'Onay Bekliyor'), ('in_progress', 'Devam Ediyor'), ('blocked', 'Blokaj'), ('done', 'Tamamlandı'), ('cancelled', 'İptal')], db_index=True, default='open', max_length=30, verbose_name='Durum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('ad_account_done', models.BooleanField(default=False, verbose_name='AD Hesabı')),
                ('mailbox_done', models.BooleanField(default=False, verbose_name='E-posta')),
                ('groups_done', models.BooleanField(default=False, verbose_name='Grup/Erişim')),
                ('endpoint_done', models.BooleanField(default=False, verbose_name='Cihaz/Zimmet')),
                ('vpn_done', models.BooleanField(default=False, verbose_name='VPN/MFA')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_lifecycle_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu IT')),
                ('directory_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_tasks', to='inventory.directoryuser', verbose_name='Directory Kullanıcısı')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_lifecycle_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name': 'Kimlik Yaşam Döngüsü İşi',
                'verbose_name_plural': 'Kimlik Yaşam Döngüsü İşleri',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
    ]
