# Generated by Django 5.2.15 on 2026-07-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_directoryconnection_directorygroup_directoryuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Departman Adı')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kod')),
                ('department_type', models.CharField(choices=[('production', 'Üretim'), ('quality', 'Kalite'), ('warehouse', 'Depo'), ('maintenance', 'Bakım'), ('administration', 'İdari İşler'), ('security', 'Güvenlik'), ('it', 'Bilgi İşlem'), ('hr', 'İnsan Kaynakları'), ('logistics', 'Lojistik'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='Tip')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('criticality', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Kritiklik')),
                ('manager_name', models.CharField(blank=True, max_length=120, verbose_name='Sorumlu')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('floor_label', models.CharField(blank=True, max_length=60, verbose_name='Kat/Bölge')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Fabrika Departmanı',
                'verbose_name_plural': 'Fabrika Departmanları',
                'ordering': ['department_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FactoryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Alan Adı')),
                ('code', models.CharField(max_length=40, verbose_name='Kod')),
                ('zone_type', models.CharField(choices=[('production_line', 'Üretim Hattı'), ('room', 'Oda'), ('server_room', 'Sistem Odası'), ('camera_zone', 'Kamera Bölgesi'), ('warehouse', 'Depo'), ('office', 'Ofis'), ('security_post', 'Güvenlik Noktası'), ('meeting', 'Toplantı'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='Alan Tipi')),
                ('floor', models.CharField(blank=True, max_length=40, verbose_name='Kat')),
                ('building', models.CharField(blank=True, max_length=80, verbose_name='Bina')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapasite')),
                ('criticality', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Kritiklik')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.factorydepartment', verbose_name='Departman')),
                ('factory_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_zones', to='inventory.factoryarea', verbose_name='Fabrika Alanı')),
            ],
            options={
                'verbose_name': 'Fabrika Alt Alanı',
                'verbose_name_plural': 'Fabrika Alt Alanları',
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ManagedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('reference_code', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Referans Kodu')),
                ('category', models.CharField(choices=[('procedure', 'Prosedür/SOP'), ('policy', 'Politika'), ('contract', 'Sözleşme'), ('manual', 'Kullanım Kılavuzu'), ('report', 'Rapor'), ('checklist', 'Checklist'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='Kategori')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint'), ('other', 'Diğer')], db_index=True, default='other', max_length=20, verbose_name='Dosya Tipi')),
                ('file', models.FileField(blank=True, null=True, upload_to='managed_documents/%Y/%m/', verbose_name='Dosya')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Boyut (byte)')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiyon')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('review', 'İncelemede'), ('approved', 'Onaylı'), ('archived', 'Arşiv')], db_index=True, default='draft', max_length=20, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tags', models.CharField(blank=True, max_length=250, verbose_name='Etiketler')),
                ('preview_enabled', models.BooleanField(default=True, verbose_name='Önizleme Açık')),
                ('external_editor_url', models.URLField(blank=True, max_length=500, verbose_name='Harici Editör URL')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='inventory.factorydepartment', verbose_name='Departman')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='inventory.factoryzone', verbose_name='Alan')),
            ],
            options={
                'verbose_name': 'Yönetilen Doküman',
                'verbose_name_plural': 'Yönetilen Dokümanlar',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FactoryITAssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('device', 'Ağ Cihazı'), ('camera', 'Kamera/NVR'), ('endpoint', 'Endpoint'), ('printer', 'Yazıcı'), ('application', 'Uygulama'), ('ticket', 'Ticket'), ('document', 'Doküman'), ('maintenance', 'Bakım İşi'), ('consumable', 'Sarf Stok'), ('asset', 'IT Varlık')], db_index=True, default='device', max_length=20, verbose_name='Varlık Tipi')),
                ('role', models.CharField(choices=[('primary', 'Birincil'), ('secondary', 'İkincil'), ('monitored', 'İzlenen'), ('backup', 'Yedek')], db_index=True, default='primary', max_length=20, verbose_name='Rol')),
                ('label', models.CharField(blank=True, max_length=180, verbose_name='Etiket')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.businessapplication', verbose_name='Uygulama')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.cameradevice', verbose_name='Kamera')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.consumableitem', verbose_name='Sarf Stok')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_relations', to='inventory.factorydepartment', verbose_name='Departman')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.device', verbose_name='Ağ Cihazı')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.endpointdevice', verbose_name='Endpoint')),
                ('it_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.itasset', verbose_name='IT Varlık')),
                ('maintenance_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.maintenancetask', verbose_name='Bakım İşi')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.printerfleetitem', verbose_name='Yazıcı')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.ticket', verbose_name='Ticket')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_relations', to='inventory.factoryzone', verbose_name='Alan')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_relations', to='inventory.manageddocument', verbose_name='Doküman')),
            ],
            options={
                'verbose_name': 'Fabrika IT Varlık İlişkisi',
                'verbose_name_plural': 'Fabrika IT Varlık İlişkileri',
                'ordering': ['asset_type', '-updated_at'],
            },
        ),
    ]
