# Generated by Django 5.2.15 on 2026-07-01 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_factorydepartment_factoryzone_manageddocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetQRTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='QR/Barkod Kodu')),
                ('tag_type', models.CharField(choices=[('device', 'Ağ Cihazı'), ('endpoint', 'Endpoint'), ('it_asset', 'IT Varlık'), ('camera', 'Kamera'), ('printer', 'Yazıcı'), ('factory_zone', 'Fabrika Alanı'), ('consumable', 'Sarf Stok')], db_index=True, default='it_asset', max_length=20, verbose_name='Etiket Tipi')),
                ('label', models.CharField(blank=True, max_length=180, verbose_name='Etiket Adı')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Fiziksel Konum')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.cameradevice', verbose_name='Kamera')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.consumableitem', verbose_name='Sarf Stok')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.device', verbose_name='Ağ Cihazı')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.endpointdevice', verbose_name='Endpoint')),
                ('factory_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.factoryzone', verbose_name='Fabrika Alanı')),
                ('it_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.itasset', verbose_name='IT Varlık')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tags', to='inventory.printerfleetitem', verbose_name='Yazıcı')),
            ],
            options={
                'verbose_name': 'Varlık QR Etiketi',
                'verbose_name_plural': 'Varlık QR Etiketleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ERPConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bağlantı Adı')),
                ('erp_type', models.CharField(choices=[('odoo', 'Odoo'), ('erpnext', 'ERPNext'), ('sap', 'SAP'), ('other', 'Diğer ERP')], db_index=True, default='odoo', max_length=20, verbose_name='ERP Tipi')),
                ('base_url', models.URLField(max_length=500, verbose_name='Sunucu URL')),
                ('database_name', models.CharField(max_length=120, verbose_name='Veritabanı')),
                ('username', models.CharField(max_length=120, verbose_name='Kullanıcı')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key / Parola')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Senkronizasyon Aktif')),
                ('sync_partners', models.BooleanField(default=True, verbose_name='Cari/Partner Sync')),
                ('sync_products', models.BooleanField(default=False, verbose_name='Ürün/Stok Sync')),
                ('sync_helpdesk', models.BooleanField(default=False, verbose_name='Helpdesk/Ticket Sync')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Sync')),
                ('last_sync_status', models.CharField(choices=[('never', 'Hiç Senkronize Edilmedi'), ('healthy', 'Sağlıklı'), ('warning', 'Uyarı'), ('error', 'Hata')], db_index=True, default='never', max_length=20, verbose_name='Sync Durumu')),
                ('last_sync_message', models.TextField(blank=True, verbose_name='Son Sync Mesajı')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='Son Sync Kayıt Sayısı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_connections', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'ERP Bağlantısı',
                'verbose_name_plural': 'ERP Bağlantıları',
                'ordering': ['erp_type', 'name'],
            },
        ),
    ]
